language: java
sudo: false
services:
  - postgresql
 postgres:
  adapter: postgresql
  database: VaidBike
  username: postgres
before_script:
  - "psql -c 'create database VaidBike;' -U postgres"
  - "rake db:migrate"
cache:
  directories:
    - "$HOME/.m2"
jdk:
  - oraclejdk8
script:
  - set -e
  - mvn clean package
  
  
